name: casual10
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.8.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.17
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=5.9.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - alembic==1.16.4
      - astunparse==1.6.3
      - attrs==25.3.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dm-tree==0.1.9
      - e==1.4.5
      - filelock==3.13.1
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - fsspec==2024.6.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.2.3
      - grpcio==1.73.1
      - h5py==3.14.0
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.1
      - keras==3.10.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.3
      - numpy==2.1.2
      - opt-einsum==3.4.0
      - optree==0.16.0
      - optuna==4.4.0
      - pandas==2.3.1
      - pillow==11.0.0
      - protobuf==5.29.5
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - rich==14.0.0
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - sqlalchemy==2.0.42
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-probability==0.25.0
      - termcolor==3.1.0
      - tf-keras==2.19.0
      - threadpoolctl==3.6.0
      - tomli==2.2.1
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - triton==3.3.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.2

